### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:106

### ISSUE THREAD

**Issue by Yang-Xijie** [lzanini/mdbook-katex#23]
Build failed. I have no hint of why this is happening.

```
$ mdbook serve (or mdbook build)
2022-02-21 16:21:52 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:106:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-02-21 16:21:53 [ERROR] (mdbook::utils): Error: The "katex" preprocessor exited unsuccessfully with exit status: 101 status
```

This is my site <https://github.com/Yang-Xijie/yang-xijie.github.io>. And I tried to build it locally on latest macOS with mdbook-katex.

**Comment by Yang-Xijie** [comment]
I have tried the smallest example like only one document with `$y=x^2$`. It works well.

**Comment by aemonk** [comment]
@Yang-Xijie how did you solve that? I have the same issue.
